apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
  namespace: student
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s-student
  replicas: 4
  template:
    metadata:
      labels:
        app: spring-boot-k8s-student
    spec:
      containers:
        - name: student-app-container
          image: 'student-app-service:6.0'
          ports:
          - containerPort: 9292
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password